spring:
  jpa:
    database:
      platform: org.hibernate.dialect.H2Dialect
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    timeOfLife: 60000
  data:
    mongodb:
      uri: mongodb://localhost:27017/usuarios
      database: usuarios
server:
  port: 8081


